### ISSUE TITLE
aiohttp is pinned to strict

### ISSUE THREAD

**Issue by frenck** [crownstone/crownstone-lib-python-sse#1]
Currently `aiohttp` is pinned to strict by this project:

https://github.com/crownstone/crownstone-lib-python-sse/blob/581b890fe5ecadd16f4d3738958432dc480e295e/requirements.txt#L1

Meaning this library isn't compatible with `aiohttp` 3.8.0, which causes a conflict/problem for the Home Assistant project.

Please relax the pinning 😄

**Comment by vliedel** [comment]
Ah, yes and split off the test dependencies, similar to https://github.com/crownstone/crownstone-lib-python-cloud

**Comment by RicArch97** [comment]
Fixed in version 2.0.3. (HA PR: https://github.com/home-assistant/core/pull/60428)
